#!/usr/bin/env bash
#script configures Nginx on a new Ubuntu machine to include a custom HTTP response header

host_name=$(hostname)
served_by="server {\n\tadd_header X-Served-By $host_name;"
redir_error="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"


apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /usr/share/nginx/html/index.html

mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo sed -i -E "s/^[^#]+location \/ \{/$redir_error/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$served_by/" /etc/nginx/sites-available/default

sudo service nginx start
