#!/usr/bin/env bash
# script configures Nginx on a new Ubuntu machine to include a custom HTTP response header

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Get the hostname of the current machine
hostname=$(hostname)

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify the default Nginx site configuration to include the custom header and other settings
sudo sed -i "s/location \/ {/location \/ {\n\tadd_header X-Served-By $hostname;/" /etc/nginx/sites-available/default
sudo sed -i "s/server {/server {\n\terror_page 404 \/custom_404.html;\n\tlocation \/redirect_me {\n\t\treturn 301 \$scheme:\/\/www.google.com;\n\t}/" /etc/nginx/sites-available/default

# Create a simple index.html file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Start Nginx service
sudo service nginx start

# Display the status to confirm Nginx is running
sudo service nginx status

