#!/usr/bin/env bash
# script installs and configures HAProxy on a new Ubuntu machine

# Update package list and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend lari-frontend
    bind *:80
    default_backend lari-backend

backend lari-backend
    balance roundrobin
    server 440367-web-01 54.160.119.223:80 check
    server 440367-web-02 18.235.243.61:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

sudo service haproxy restart
